name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.12.x
        include:
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.12.0+domains
            dune-cache: false
            opam-repositories: |
              multicore: https://github.com/ocaml-multicore/multicore-opam.git
              default: https://github.com/ocaml/opam-repository.git
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.12.0+domains+effects
            dune-cache: false
            opam-repositories: |
              multicore: https://github.com/ocaml-multicore/multicore-opam.git
              default: https://github.com/ocaml/opam-repository.git

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test
          opam-repositories: ${{ matrix.opam-repositories }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
